(function(n,w,p){if("object"===typeof p&&"string"!==typeof p.nodeName)w(n,p);else{var v=function(b){for(var k in b)b.hasOwnProperty(k)&&(b[k]=v(b[k]));return Object.freeze(b)};p={};w(n,p);for(var q in p)!p.hasOwnProperty(q)||null!=Object.getOwnPropertyDescriptor(n,q)&&null!=Object.getOwnPropertyDescriptor(n[q],"1.2.6-iab634")||(null==Object.getOwnPropertyDescriptor(n,q)&&Object.defineProperty(n,q,{value:{}}),Object.defineProperty(n[q],"1.2.6-iab634",{get:function(){return v(p[q])},enumerable:!0}))}})("undefined"===
typeof global?this:global,function(n,w){function p(a,d){return a&&(a[d]||(a[d]={}))}function v(a,d){"undefined"!==typeof jasmine&&jasmine?a():"undefined"!==typeof console&&console&&console.error&&d()}function q(a,d){return d.reduce(function(a,d){return a&&a[d]},a)}var b=b||{};b.scope={};b.inherits=function(a,d){function c(){}c.prototype=d.prototype;a.superClass_=d.prototype;a.prototype=new c;a.prototype.constructor=a;for(var b in d)if("prototype"!=b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(d,
b);e&&Object.defineProperty(a,b,e)}else a[b]=d[b]};b.ASSUME_ES5=!1;b.ASSUME_NO_NATIVE_MAP=!1;b.ASSUME_NO_NATIVE_SET=!1;b.defineProperty=b.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)};b.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};b.global=b.getGlobal(this);b.SYMBOL_PREFIX="jscomp_symbol_";b.initSymbol=function(){b.initSymbol=
function(){};b.global.Symbol||(b.global.Symbol=b.Symbol)};b.symbolCounter_=0;b.Symbol=function(a){return b.SYMBOL_PREFIX+(a||"")+b.symbolCounter_++};b.initSymbolIterator=function(){b.initSymbol();var a=b.global.Symbol.iterator;a||(a=b.global.Symbol.iterator=b.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&b.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return b.arrayIterator(this)}});b.initSymbolIterator=function(){}};b.arrayIterator=function(a){var d=
0;return b.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};b.iteratorPrototype=function(a){b.initSymbolIterator();a={next:a};a[b.global.Symbol.iterator]=function(){return this};return a};b.makeIterator=function(a){b.initSymbolIterator();var d=a[Symbol.iterator];return d?d.call(a):b.arrayIterator(a)};b.arrayFromIterator=function(a){for(var d,c=[];!(d=a.next()).done;)c.push(d.value);return c};b.arrayFromIterable=function(a){return a instanceof Array?a:b.arrayFromIterator(b.makeIterator(a))};
var k={assertTruthyString:function(a,d){if(!d)throw Error("Value for "+a+" is undefined, null or blank.");if("string"!==typeof d&&!(d instanceof String))throw Error("Value for "+a+" is not a string.");if(""===d.trim())throw Error("Value for "+a+" is empty string.");},assertNotNullObject:function(a,d){if(null==d)throw Error("Value for "+a+" is undefined or null");},assertNumber:function(a,d){if(null==d)throw Error(a+" must not be null or undefined.");if("number"!==typeof d||isNaN(d))throw Error("Value for "+
a+" is not a number");},assertNumberBetween:function(a,d,c,b){(0,k.assertNumber)(a,d);if(d<c||d>b)throw Error("Value for "+a+" is outside the range ["+c+","+b+"]");},assertFunction:function(a,d){if(!d)throw Error(a+" must not be truthy.");},assertPositiveNumber:function(a,d){(0,k.assertNumber)(a,d);if(0>d)throw Error(a+" must be a positive number.");}};var t=function(a){return/\d+\.\d+\.\d+(-.*)?/.test(a)};var u=function(a,d){a=a.split("-")[0].split(".");d=d.split("-")[0].split(".");for(var c=0;3>
c;c++){var b=parseInt(a[c],10),e=parseInt(d[c],10);if(b>e)break;else if(b<e)return!1}return!0};var A=function(a,d){return(0,t)(a)&&(0,u)(a,"1.0.3")?d:JSON.stringify(d)};var y=function(a,d){return(0,t)(a)&&(0,u)(a,"1.0.3")?d?d:[]:d&&"string"===typeof d?JSON.parse(d):[]};var m=function(a,d,c,b){this.guid=a;this.method=d;this.version=c;this.args=b};m.isValidSerializedMessage=function(a){return!!a&&void 0!==a.omid_message_guid&&void 0!==a.omid_message_method&&void 0!==a.omid_message_version&&"string"===
typeof a.omid_message_guid&&"string"===typeof a.omid_message_method&&"string"===typeof a.omid_message_version&&(void 0===a.omid_message_args||void 0!==a.omid_message_args)};m.deserialize=function(a){return new m(a.omid_message_guid,a.omid_message_method,a.omid_message_version,a.omid_message_args)};m.prototype.serialize=function(){var a={};a=(a.omid_message_guid=this.guid,a.omid_message_method=this.method,a.omid_message_version=this.version,a);void 0!==this.args&&(a.omid_message_args=this.args);return a};
var g=function(a){this.to=a;this.communicationType_="NONE"};g.prototype.sendMessage=function(a,d){};g.prototype.handleMessage=function(a,d){if(this.onMessage)this.onMessage(a,d)};g.prototype.generateGuid=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var d=16*Math.random()|0;return a="y"===a?(d&3|8).toString(16):d.toString(16)})};g.prototype.serialize=function(a){return JSON.stringify(a)};g.prototype.deserialize=function(a){return JSON.parse(a)};g.prototype.isDirectCommunication=
function(){return"DIRECT"===this.communicationType_};var c={OMID_PRESENT_FRAME_NAME:"omid_v1_present",isOmidPresent:function(a){try{return a.frames?!!a.frames[c.OMID_PRESENT_FRAME_NAME]:!1}catch(d){return!1}},declareOmidPresence:function(a){a.frames&&a.document&&(c.OMID_PRESENT_FRAME_NAME in a.frames||(null==a.document.body&&c.isMutationObserverAvailable_(a)?c.registerMutationObserver_(a):a.document.body?c.appendPresenceIframe_(a):a.document.write('<iframe style="display:none" '+('id="'+c.OMID_PRESENT_FRAME_NAME+
'"')+(' name="'+c.OMID_PRESENT_FRAME_NAME+'">')+"</iframe>")))},appendPresenceIframe_:function(a){var d=a.document.createElement("iframe");d.id=c.OMID_PRESENT_FRAME_NAME;d.name=c.OMID_PRESENT_FRAME_NAME;d.style.display="none";a.document.body.appendChild(d)},isMutationObserverAvailable_:function(a){return"MutationObserver"in a},registerMutationObserver_:function(a){var d=new MutationObserver(function(b){b.forEach(function(b){"BODY"===b.addedNodes[0].nodeName&&(c.appendPresenceIframe_(a),d.disconnect())})});
d.observe(a.document.documentElement,{childList:!0})}},e=function(a){g.call(this,a);this.communicationType_="DIRECT";this.handleExportedMessage=e.prototype.handleExportedMessage.bind(this)};b.inherits(e,g);e.prototype.sendMessage=function(a,d){d=void 0===d?this.to:d;if(!d)throw Error("Message destination must be defined at construction time or when sending the message.");d.handleExportedMessage(a.serialize(),this)};e.prototype.handleExportedMessage=function(a,d){m.isValidSerializedMessage(a)&&this.handleMessage(m.deserialize(a),
d)};var f={error:function(a){for(var d=[],c=0;c<arguments.length;++c)d[c-0]=arguments[c];v(function(){throw new (Function.prototype.bind.apply(Error,[null].concat(["Could not complete the test successfully - "],b.arrayFromIterable(d))));},function(){return console.error.apply(console,[].concat(b.arrayFromIterable(d)))})},debug:function(a){for(var d=[],c=0;c<arguments.length;++c)d[c-0]=arguments[c];v(function(){},function(){return console.error.apply(console,[].concat(b.arrayFromIterable(d)))})}},
r=eval("this");var h=function(){if("undefined"!==typeof n&&n)return n;if("undefined"!==typeof global&&global)return global;if("undefined"!==typeof window&&window)return window;if("undefined"!==typeof r&&r)return r;throw Error("Could not determine global object context.");}();var z=function(a,d){d=void 0===d?h:d;g.call(this,d);var c=this;this.communicationType_="POST_MESSAGE";a.addEventListener("message",function(a){if("object"===typeof a.data){var d=a.data;m.isValidSerializedMessage(d)&&(d=m.deserialize(d),
a.source&&c.handleMessage(d,a.source))}})};b.inherits(z,g);z.isCompatibleContext=function(a){return!!(a&&a.addEventListener&&a.postMessage)};z.prototype.sendMessage=function(a,d){d=void 0===d?this.to:d;if(!d)throw Error("Message destination must be defined at construction time or when sending the message.");d.postMessage(a.serialize(),"*")};var x=function(a){"undefined"===typeof a&&"undefined"!==typeof window&&window&&(a=window);if("undefined"===typeof a||!a||"undefined"===typeof a.top||!a.top)return h;
if(a===a.top)return a;try{return"undefined"===typeof a.top.location.hostname?a:a.top}catch(d){return a}};var B=function(a,d,b){b=void 0===b?c.isOmidPresent:b;return(d=q(a,d))?new e(d):a.top&&b(a.top)?new z(a,a.top):null};var l=function(a){if(this.communication=void 0===a?(0,B)((0,x)(),["omid","v1_VerificationServiceCommunication"]):a)this.communication.onMessage=this.handleMessage_.bind(this);else if(a=(a=h.omid3p)&&"function"===typeof a.registerSessionObserver&&"function"===typeof a.addEventListener?
a:null)this.omid3p=a;this.remoteIntervals_=this.remoteTimeouts_=0;this.callbackMap_={};this.imgCache_=[]};l.prototype.isSupported=function(){return!!this.communication};l.prototype.registerSessionObserver=function(a,d){(0,k.assertFunction)("functionToExecute",a);this.omid3p?this.omid3p.registerSessionObserver(a,d):this.sendMessage_("addSessionListener",a,d)};l.prototype.addEventListener=function(a,d){(0,k.assertTruthyString)("eventType",a);(0,k.assertFunction)("functionToExecute",d);this.omid3p?this.omid3p.addEventListener(a,
d):this.sendMessage_("addEventListener",d,a)};l.prototype.sendUrl=function(a,d,c){(0,k.assertTruthyString)("url",a);h.document&&h.document.createElement?this.sendUrlWithImg_(a,d,c):this.sendMessage_("sendUrl",function(a){a&&d?d():!a&&c&&c()},a)};l.prototype.sendUrlWithImg_=function(a,d,c){var b=this,e=h.document.createElement("img");this.imgCache_.push(e);var f=function(a){var d=b.imgCache_.indexOf(e);0<=d&&b.imgCache_.splice(d,1);a&&a()};e.addEventListener("load",f.bind(this,d));e.addEventListener("error",
f.bind(this,c));e.src=a};l.prototype.injectJavaScriptResource=function(a,d,c){var b=this;(0,k.assertTruthyString)("url",a);h.document?this.injectJavascriptResourceUrlInDom_(a,d,c):this.sendMessage_("injectJavaScriptResource",function(e,h){e?(b.evaluateJavaScript_(h,a),d()):(f.error("Service failed to load JavaScript resource."),c())},a)};l.prototype.injectJavascriptResourceUrlInDom_=function(a,d,c){var b=h.document,e=b.body;b=b.createElement("script");b.onload=d;b.onerror=c;b.src=a;b.type="application/javascript";
e.appendChild(b)};l.prototype.evaluateJavaScript_=function(a,d){try{eval(a)}catch(C){f.error('Error evaluating the JavaScript resource from "'+d+'".')}};l.prototype.setTimeout=function(a,d){(0,k.assertFunction)("functionToExecute",a);(0,k.assertPositiveNumber)("timeInMillis",d);if(this.hasTimeoutMethods_())return h.setTimeout(a,d);var c=this.remoteTimeouts_++;this.sendMessage_("setTimeout",a,c,d);return c};l.prototype.clearTimeout=function(a){(0,k.assertPositiveNumber)("timeoutId",a);this.hasTimeoutMethods_()?
h.clearTimeout(a):this.sendOneWayMessage_("clearTimeout",a)};l.prototype.setInterval=function(a,d){(0,k.assertFunction)("functionToExecute",a);(0,k.assertPositiveNumber)("timeInMillis",d);if(this.hasIntervalMethods_())return h.setInterval(a,d);var c=this.remoteIntervals_++;this.sendMessage_("setInterval",a,c,d);return c};l.prototype.clearInterval=function(a){(0,k.assertPositiveNumber)("intervalId",a);this.hasIntervalMethods_()?h.clearInterval(a):this.sendOneWayMessage_("clearInterval",a)};l.prototype.hasTimeoutMethods_=
function(){return"function"===typeof h.setTimeout&&"function"===typeof h.clearTimeout};l.prototype.hasIntervalMethods_=function(){return"function"===typeof h.setInterval&&"function"===typeof h.clearInterval};l.prototype.handleMessage_=function(a,d){d=a.method;var c=a.guid;a=a.args;if("response"===d&&this.callbackMap_[c]){var b=(0,y)("1.2.6-iab634",a);this.callbackMap_[c].apply(this,b)}"error"===d&&window.console&&f.error(a)};l.prototype.sendOneWayMessage_=function(a,d){for(var c=[],e=1;e<arguments.length;++e)c[e-
1]=arguments[e];this.sendMessage_.apply(this,[].concat([a,null],b.arrayFromIterable(c)))};l.prototype.sendMessage_=function(a,d,c){for(var b=[],e=2;e<arguments.length;++e)b[e-2]=arguments[e];this.communication&&(e=this.communication.generateGuid(),d&&(this.callbackMap_[e]=d),b=new m(e,"VerificationService."+a,"1.2.6-iab634",(0,A)("1.2.6-iab634",b)),this.communication.sendMessage(b))};(0,function(a,d,c){if(c=void 0===c?"undefined"===typeof w?null:w:c)a=a.split("."),a.slice(0,a.length-1).reduce(p,c)[a[a.length-
1]]=d})("OmidVerificationClient",l)},"undefined"===typeof exports?void 0:exports);
(function(){function n(){var c={location:{protocol:"https:"}};c.parent=c;c.top=c;c.document={getElementById:function(){},createElement:function(){},body:{insertBefore:function(){}},querySelectorAll:function(){return[]}};return c}function w(c,b){var e=g.getReportUrl(g.ErrorTypes.LoadTagError,"failedToLoadDVM",!0),r=c&&(c.contentDocument||c.contentWindow&&c.contentWindow.document||frames&&frames[c.name]&&frames[c.name].document);b='<html><head><script type="text/javascript">('+function(){window.$dv=
window.parent.$dv;window.$dv.isFrameSupported=!0;window.$frmId=Math.random().toString(36)+Math.random().toString(36);window.dv_flow=2}.toString()+')();\x3c/script></head><body><script type="text/javascript">('+function(c,b){if(c){var e=document.createElement("script");e.src=c;e.onerror=function(){(new Image(1,1)).src=b};document.body.appendChild(e)}}.toString()+')("'+b+'", "'+e+'");\x3c/script></body></html>';r?(r.open(),r.write(b),r.close()):(r=encodeURIComponent(b.replace(/'/g,"\\'").replace(/\n|\r\n|\r/g,
"")),c.src='javascript: (function(){document.open();document.domain="'+window.document.domain+"\";document.write('"+r+"');})()")}function p(c){var b=Math.floor(1E12*(Math.random()+"")),f=document.createElement("iframe");f.name=f.id="iframe_"+b;f.setAttribute("data-dv-frm",b);f.width="0";f.height="0";f.style.display="none";f.src="about:blank";document.currentScript?document.currentScript.parentNode.insertBefore(f,document.currentScript):document.body?document.body.insertBefore(f,document.body.firstChild):
(b=document.getElementsByTagName("head")[0],b.insertBefore(f,b.firstChild));w(f,c)}function v(c,b){$frmId=Math.random().toString(36)+Math.random().toString(36);c.injectJavaScriptResource(b,function(){},function(){var b=g.getReportUrl(g.ErrorTypes.OmidLoadTagError,"",!0);c.sendUrl(b)})}function q(c){try{(new Image(1,1)).src=c}catch(e){}}function b(c,b,f){c||(c={message:"error undefined"});c=["https://tps.doubleverify.com/visit.jpg?ctx=818052&cmp=1619415&dvtagver=6.1.src&dvp_isLostImp=",f,"&dvp_jsErrMsg=",
c.message,"&napr=",c.message,"&cerrt=",b,"&jsver=",t&&t.getNewestVersion()].join("");k&&(c+="&dvp_idle=1");u.isSupported()&&(c+="&dvp_iomd=1");c=encodeURI(c);u.isSupported()?u.report(c):q(c)}dv_flow=2;var k=!1;"undefined"===typeof window&&(k=!0);var t=function(){var c,b,f,r=function(){var e=[{src:"dv-measurements",main:338}];c=(b=e&&e[0])&&b.eval&&b.rate&&100*Math.random()<b.rate?b.eval:b.main;f=b&&(b.eval?b.eval:b.main)};return{getNewestVersion:function(){try{return b||r(),f}catch(h){return 0}},
getMeasurementsScriptUrl:function(e){b||r();return c&&b&&[e,"//cdn.doubleverify.com/",b.src,c,".js"].join("")}}}(),u={omidObject:null,isOmidSupported:null,report:function(c){this.omidObject&&"function"===typeof this.omidObject.sendUrl?(this.omidObject.sendUrl(c),k&&"object"===typeof omidNative&&"function"===typeof omidNative.sendUrl&&omidNative.sendUrl(c+"&dvp_ionsu=1")):q(c)},isSupported:function(){if(null!==this.isOmidSupported&&void 0!==this.isOmidSupported)return this.isOmidSupported;try{this.omidObject||
(this.omidObject=new OmidVerificationClient["1.2.6-iab634"]),this.isOmidSupported=this.omidObject.isSupported()}catch(e){if(this.isOmidSupported=!1,g){var c=g.getReportUrl(g.ErrorTypes.OmidUnexpectedError,"isSupported__"+e.message,!1);this.report(c)}}return this.isOmidSupported},getVendorKey:function(){if(!k&&m){var c=(c=m.getQueryStringParams())&&c.vendor_key;window.$dv.omidVendorKeyExtracted=Number(!!c)}return c||"doubleverify.com-omid"},execute:function(){var c=this,b=this.omidObject;"undefined"!=
typeof $dv?($dv.tagsCounter=$dv.tagsCounter||0,$dv.tagsCounter++,$dv.omidJsClient=b):$dv={omidJsClient:b,tags:{},tagsCounter:1};$dv.isDomlessEnvironment=k;var f=this.getVendorKey();$dv.omidVendorKey=f;k&&(window=n());b.registerSessionObserver(function(e){try{switch(e.type){case "sessionStart":$dv.omidSessionData=e;$dv.omidAccessMode=e&&e.data&&e.data.context&&e.data.context.accessMode;try{$dv.omidSessionStartTime=Date.now?Date.now():(new Date).getTime()}catch(x){var h=g.getReportUrl(g.ErrorTypes.OmidUnexpectedError,
"Date.now__"+x.message,!1);b.sendUrl(h)}var f=t.getMeasurementsScriptUrl("https:");if($dv.isDomlessEnvironment)v(b,f);else try{p(f)}catch(x){h=g.getReportUrl(g.ErrorTypes.OmidUnexpectedError,"injectScriptSteps__"+x.message,!1),b.sendUrl(h),v(b,f)}break;case "sessionError":h=g.getReportUrl(g.ErrorTypes.OmidSessionError,e.data&&e.data.message||"",!0),c.report(h)}}catch(x){e=g.getReportUrl(g.ErrorTypes.OmidUnexpectedLostImpError,"omidCallback__"+x.message,!0),b.sendUrl(e)}},f)}},A={execute:function(){try{window.$dv=
window.$dv||{tags:{}};var b=document.currentScript&&0==document.currentScript.src.indexOf("http:")?"http:":"https:";var e=t.getMeasurementsScriptUrl(b);p(e)}catch(f){g.report(g.ErrorTypes.InjectTagError,f.message,!0)}}},y="";try{y=window&&window.document&&window.document.currentScript&&window.document.currentScript.src}catch(c){}try{var m=function(b){function c(b){var c={};b.split("&").forEach(function(b){b=b.trim().split("=");2===b.length&&(c[b[0].trim()]=b[1].trim())});return c}function f(b){var c=
{};["cmp","ctx","sid","plc"].forEach(function(e){b.hasOwnProperty(e)&&(c["dvp_"+e]=b[e])});return c}var g={},h={};(function(b){if(b){var e="";b=b.trim().split("?");2===b.length&&(e=b[1]);e&&(g=c(e),h=f(g))}})(b);return{toQueryString:function(b){var c="",e;for(e in b)b.hasOwnProperty(e)&&(c&&(c+="&"),c=[c,e,"=",b[e]].join(""));return c},getQueryStringParams:function(){return g},getQueryStringClientParams:function(){return h}}}(y);var g=function(){function b(b,c,f){c=(c=c&&c&&c.trim().replace(/(\t|\n|\r|\|)/g,
""))&&encodeURIComponent(c)||"";c=e.replace(/__ERR_MSG_PLACEHOLDR__/g,[b.message,c].join("__"));c=c.replace(/__CLIENT_ERROR_TYPE_PLACEHOLDR__/g,b.id);f&&(c+="&dvp_isLostImp=1");u.isSupported()&&(c+="&dvp_iomd=1");return c}var e="",f={ctx:818052,cmp:1619415,dvtagver:"6.1.src",jsver:t&&t.getNewestVersion(),dvp_jsErrMsg:"__ERR_MSG_PLACEHOLDR__",napr:"__ERR_MSG_PLACEHOLDR__",cerrt:"__CLIENT_ERROR_TYPE_PLACEHOLDR__"};k&&(f.dvp_idle=1);e=["https://tps.doubleverify.com/visit.jpg?",[m.toQueryString(f),m.toQueryString(m.getQueryStringClientParams())].join("&")].join("");
return{ErrorTypes:{OmidNativeCollectData:{id:512,message:"OmidNativeCollectData"},InjectTagError:{id:1,message:"InjectTagError"},LoadTagError:{id:2,message:"LoadTagError"},UnexpectedLostImpError:{id:4,message:"UnexpectedLostImpError"},OmidSessionError:{id:8,message:"OmidSessionError"},OmidUnexpectedLostImpError:{id:16,message:"OmidUnexpectedLostImpError"},OmidLoadTagError:{id:32,message:"OmidLoadTagError"},OmidInjectTagError:{id:64,message:"OmidInjectTagError "},UnexpectedError:{id:128,message:"UnexpectedError"},
OmidUnexpectedError:{id:256,message:"OmidUnexpectedError"}},report:function(c,e,f){q(b(c,e,f))},getReportUrl:b}}()}catch(c){b(c,128,0)}try{(u.isSupported()?u:A).execute()}catch(c){g?g.report(g.ErrorTypes.UnexpectedLostImpError,c.message,!0):b(c,4,1)}})();
